# Generated by Django 4.2.7 on 2023-11-12 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hyg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('code', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('price', models.FloatField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyg.products')),
            ],
            options={
                'verbose_name': 'ProductoVendido',
                'verbose_name_plural': 'ProductosVendidos',
                'db_table': 'ProductoVendido',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateandhour', models.DateTimeField(null=True)),
                ('products', models.ManyToManyField(through='sales.ProductSold', to='hyg.products')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'db_table': 'ventas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='productsold',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sale'),
        ),
    ]
