# Generated by Django 4.2.7 on 2023-12-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
