# Generated by Django 4.2.6 on 2023-11-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadc', models.IntegerField()),
                ('fechac', models.DateField(blank=True, null=True)),
                ('precioc', models.IntegerField()),
                ('productoc', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
