# Generated by Django 4.2.7 on 2023-11-07 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_gastos_producto_productovendido_role_user_userrole_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['id'], 'verbose_name': 'compra', 'verbose_name_plural': 'compras'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['id'], 'verbose_name': 'proveedor', 'verbose_name_plural': 'proveedores'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['id'], 'verbose_name': 'venta', 'verbose_name_plural': 'ventas'},
        ),
        migrations.AlterModelTable(
            name='compra',
            table='compras',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='proveedor',
        ),
        migrations.AlterModelTable(
            name='venta',
            table='ventas',
        ),
    ]
