# Generated by Django 4.2.7 on 2023-11-07 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_compra_options_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gastos',
            options={'ordering': ['id'], 'verbose_name': 'gasto', 'verbose_name_plural': 'gastos'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['id'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productovendido',
            options={'ordering': ['id'], 'verbose_name': 'ProductoVendido', 'verbose_name_plural': 'ProductosVendidos'},
        ),
        migrations.AlterModelTable(
            name='gastos',
            table='gastos',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='Producto',
        ),
        migrations.AlterModelTable(
            name='productovendido',
            table='ProductoVendido',
        ),
    ]
