# Generated by Django 4.2.7 on 2023-11-13 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='productc',
        ),
    ]
