# Generated by Django 4.2.6 on 2023-11-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='name',
        ),
        migrations.AddField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
