# Generated by Django 4.2.6 on 2023-11-09 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyg', '0002_remove_products_name_products_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='name',
        ),
    ]
