# Generated by Django 4.2.7 on 2023-12-08 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hyg', '0003_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
